version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - echo "Building application..."
      - mvn clean install -DskipTests=true
  post_build:
    commands:
      - echo "Packaging application for deployment..."
      - mv target/*.jar demo.jar
      - echo "Running the application..."
      - java -jar demo.jar
artifacts:
  files:
    - MyApp.jar